const MOCK_DATE = '2024-01-01T00:00:00.000Z';

export const MOCK_PRODUCTS = [
  {
    id: 'mock-1',
    name: 'Romantic Bouquets',
    slug: 'romantic-bouquets',
    tag: 'Bestseller',
    description: 'Red, pink, and white rose arrangements for anniversaries, birthdays, apologies, and romantic gestures.',
    image_url: '/images/mixed_bouquet.png',
    image_urls: ['/images/mixed_bouquet.png'],
    price_usd: null,
    is_active: true,
    sort_order: 1,
    created_at: MOCK_DATE,
    updated_at: MOCK_DATE,
  },
  {
    id: 'mock-2',
    name: 'Floral Gift Boxes',
    slug: 'floral-gift-boxes',
    tag: 'Signature',
    description: 'Elegant boxed flowers for gifting, available with a personal card message and custom color direction.',
    image_url: '/images/flower_box.png',
    image_urls: ['/images/flower_box.png'],
    price_usd: null,
    is_active: true,
    sort_order: 2,
    created_at: MOCK_DATE,
    updated_at: MOCK_DATE,
  },
  {
    id: 'mock-3',
    name: 'Mixed Arrangements',
    slug: 'mixed-arrangements',
    tag: 'Seasonal',
    description: 'Seasonal mixed blooms with joyful color, arranged fresh based on what is best in the shop that day.',
    image_url: '/images/mixed_bouquet.png',
    image_urls: ['/images/mixed_bouquet.png'],
    price_usd: null,
    is_active: true,
    sort_order: 3,
    created_at: MOCK_DATE,
    updated_at: MOCK_DATE,
  },
  {
    id: 'mock-4',
    name: 'Heart Arrangements',
    slug: 'heart-arrangements',
    tag: 'Special',
    description: "Heart-shaped rose displays for Valentine's Day, Mother's Day, proposals, and statement gifts.",
    image_url: '/images/heart_roses.png',
    image_urls: ['/images/heart_roses.png'],
    price_usd: null,
    is_active: true,
    sort_order: 4,
    created_at: MOCK_DATE,
    updated_at: MOCK_DATE,
  },
];
